### ISSUE TITLE
nit: variance unit

### ISSUE THREAD

**Issue by truher** [yumashino/Camera-Calibration-with-ChArUco-Board#1]
https://github.com/yumashino/Camera-Calibration-with-ChArUco-Board/blob/8d3320777bbe39141169de8cdb205525274eacf8/calibrate_camera_with_charuco.py#L71

hey, i love that you put this up, thank you!  i did fine one tiny error that you might want to know about, the units of variance are squared so to convert to meters you have to divide by 1e6 not 1e3.

thanks again!

**Comment by yumashino** [comment]
That's exactly right! I have committed the revised version (https://github.com/yumashino/Camera-Calibration-with-ChArUco-Board/commit/1d05012b4d1d168c68b37944d8585d624760293f). 
Thank you!

**Comment by yumashino** [comment]
That's exactly right! I have committed the revised version (https://github.com/yumashino/Camera-Calibration-with-ChArUco-Board/commit/1d05012b4d1d168c68b37944d8585d624760293f).
Thank you!
